#ifndef __EFONT_UTF16_PROGMEM_DISABLE_ALL_H__
#define __EFONT_UTF16_PROGMEM_DISABLE_ALL_H__

#define __EFONT_UTF16_PROGMEM_DISABLE_0XAC__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XAD__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XAE__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XAF__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB0__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB1__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB2__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB3__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB4__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB5__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB6__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB7__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB8__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XB9__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XBA__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XBB__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XBC__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XBD__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XBE__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XBF__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC0__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC1__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC2__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC3__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC4__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC5__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC6__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC7__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC8__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XC9__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XCA__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XCB__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XCC__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XCD__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XCE__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XCF__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD0__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD1__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD2__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD3__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD4__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD5__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD6__    // Hang
#define __EFONT_UTF16_PROGMEM_DISABLE_0XD7__    // Hang

#endif
